# Generated by Django 5.2.10 on 2026-03-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_5', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='unique_success_payment_per_order_day_8',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['success', 'processing'])), fields=('order',), name='unique_success_payment_per_order_day_8'),
        ),
    ]
